# Generated by Django 2.1.1 on 2018-09-15 17:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180915_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='search_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=2), size=5),
        ),
    ]
