# Generated by Django 2.1.1 on 2018-09-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180915_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='current_city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
