# Generated by Django 2.1 on 2018-09-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('sunrise', models.DateTimeField(verbose_name='sunrise time')),
                ('sunset', models.DateTimeField(verbose_name='sunset time')),
            ],
        ),
    ]
