# Generated by Django 2.1.1 on 2018-09-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityWeather',
        ),
    ]
